export const metadata = {
    // title: "Create Next App",
    title: {
      absolute:'bbssb',
    },
    description: "Generated by create next app",
  };


  
export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body>
             { children }
        </body>
      </html>
    );
  }