import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  // title: "Create Next App",
  title: {
    default:'العنوان بيكون فأي صفحة فش فيها ميتاداتا',
    template:'%s + نص  [البرسنتج يعني اي اسم ميتا داتا انت معرفها فبيج بالاضافة للنص]',
    absolute:'هاي فالبيجز اللي بدكاش تقبل البرسنتج'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen `}
      >
        <div className="h-12 bg-slate-500 flex justify-center items-center">Header</div>
        <div className="flex-grow mx-auto">
             {children}
        </div>
        <Link href={'/'} className="cursor-pointer bg-yellow-600 text-white p-6 w-fit mx-auto mb-4 flex justify-center items-center">
          <button>Home Page</button>
        </Link>
        
        <div className="h-12 bg-slate-500 flex justify-center items-center ">footer</div>
      </body>
    </html>
  );
}
